In [ ]:
import  torch

In [ ]:
# FIRST PARTERN:  DIRECT CREATION FROM DATA

# Input a standard Python list

data = [[3,2,1],[4,5,2]]
my_tensor = torch.tensor(data)
print(my_tensor)

tensor([[3, 2, 1],
        [4, 5, 2]])


In [ ]:
# SECOND PARTERN:  CREATION FROM A DESIRE SHAPES

# Input: A shape tuple (2rows 3cols)

shape = (2,3)
ones = torch.ones(shape)
zeros = zeros = torch.zeros(shape)
random = random = torch.rand(shape)

print(ones)
print(zeros)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5205, 0.9551, 0.0888],
        [0.1996, 0.0164, 0.7003]])


In [ ]:
# THIRD PARTERN:  CREATION BY MIMICKING ANOTHER TENSOR

# Input: A 'template' tensor
template = torch.tensor ([[1,2],[3,4]])

#Create a new tensor with the same properties
rand_like = torch.rand_like(template, dtype=torch.float)

print(f"Template Tensor:\n {template}\n")

print(f"Random Tensor:\n {rand_like}")

Template Tensor:
 tensor([[1, 2],
        [3, 4]])

Random Tensor:
 tensor([[0.5236, 0.0377],
        [0.0091, 0.3070]])


In [ ]:
tensor = torch.randn(2,9)
print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device: {tensor.device}")

Shape: torch.Size([2, 9])
Datatype: torch.float32
Device: cpu


**.shape**: a tuple describimng the dimensions. my #1 debigging tool

**.device:** where the tensor lives, cpu or cuda (GPU)


*> By default, a tensor is just data, to tell pytorch its a learneable parameter:*

**requires_grad=True**



In [44]:
#BUILDING THE GRAPH

#GOAL COMPUTE:  z = x * y, where y = a + b

a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

In [54]:
y = a + b
print(f"Resultado: {y}")

Resultado: 5.0


In [55]:
z = x * y
print(f"Resultado: {z}")

Resultado: 20.0


In [59]:
print(z.grad_fn) #created by *
print(y.grad_fn) #created by +
print(a.grad_fn) #created by tensor (user)
print(b.grad_fn) #created by tensor (user)
print(x.grad_fn) #created by tensor (user)

None
None
None


In [62]:
# ELEMENT-WISE MULTIPLICATION *

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[10,20],[30,40]])

element_wise_multi = a * b
print(f"Resultado: {element_wise_multi}")

Reesultado: tensor([[ 10,  40],
        [ 90, 160]])


In [64]:
# MATRIX MULTIPLICATION @

#Rule: m1 columns = m2 rows

m1 = torch.tensor([[1,2,3],[4,5,6]]) #Shape:(2,3)
m2 = torch.tensor([[7,8],[9,10],[11,12]]) #Shape:(3,2)

matrix_product = m1 @ m2
print(f"Resultado: {matrix_product}")


Resultado: tensor([[ 58,  64],
        [139, 154]])


In [66]:
#REAL EXAMPLE PART 1

scores = torch.tensor([[10.,20.,30.],[5.,10.,15.]])
average_score = scores.mean() #average calc
print(f"Resultado: {average_score}")

Resultado: 15.0


In [ ]:
## RULE FOR 2D TENSORS

# dim=0 --> rows (horizontal)
# dim=1 --> cols (vertical)

In [71]:
#REAL EXAMPLE PART 2

# NOW SCORES IMAGINE IS: 2 STUDENTS, 3 ASSIGNMNENTS --> shape(2,3)

#SCORES	      ASSIGNMNENT 1	ASSIGNMNENT 2	ASSIGNMNENT 3
#STUDENT 1	  10	          20	          30
#STUDENT 2	  5	            10	          15

scores = torch.tensor([[10.,20.,30.],[5.,10.,15.]])

# calculating average by dimension
scores = torch.tensor([[10.,20.,30.],[5.,10.,15.]])

#to get the average FOR EACH ASSIGNMENT, we collapse the assignment/horizontal dimension  --> (dim=0)
average_score_by_student = scores.mean(dim=0)
#to get the average FOR EACH STUDENT, we collapse the student/vertical dimension  --> (dim=1)
average_score_by_assignment = scores.mean(dim=1)

print(f"Average per assingment (dim=0): {average_score_by_student}")
print(f"Average per student (dim=1): {average_score_by_assignment}")



Average per assingment (dim=0): tensor([ 7.5000, 15.0000, 22.5000])
Average per student (dim=1): tensor([20., 10.])


In [77]:
#BASIC INDEXING

x = torch.arange(12).reshape(3,4)

# tensor([[0, 1,  2,  3],
#         [4, 5,  6,  7],
#         [8, 9,  10  11]])

#Get the third column (at indez 2)
col_2 = x[:,2]
print(col_2)

# Get the last column using negative indexing
last_col = x[:, -1]
print(last_col)

# Get the first two rows and the middle two columns Rows 0 and 1 | Columns 1 and 2
#We can select a specific "block" or "sub-tensor" by defining a range start:end. The end index IS NOT INCLUDED!

sub_tensor = x[0:2, 1:3]
print(sub_tensor)

# Get all values in the tensor that are greater than 7
mask = x > 7
filtered_elements = x[mask]
print(filtered_elements)

tensor([ 2,  6, 10])
tensor([ 3,  7, 11])
tensor([[1, 2],
        [5, 6]])
tensor([ 8,  9, 10, 11])


In [79]:
## DYNAMIC SELECTION: ARGMAX()

scores = torch.tensor([
          # Best scoree is at index 2
          [10, 0,  20,  1],
          # Best scoree is at index 1
          [1, 30,  5,  0],
])

#Find the index of th best score for each
best_indices = torch.argmax(scores, dim=1)
print(best_indices)

tensor([2, 1])


In [81]:
## EXPERT SELECTION: TORCH.GATHER()

data = torch.tensor([
          [10, 11,  12,  13],   #row 1 index=0
          [20, 21,  22,  23],   #row 2 index=1
          [30, 31,  32,  33]    #row 3 index=2
])

# Our "shopping list" of which column to get from each row
indices_to_select = torch.tensor([[2],[0],[3]])

#Gather from "data" along dim=1 (cols)
selected_columns = torch.gather(data, dim=1, index=indices_to_select)


print(selected_columns)

tensor([[12],
        [20],
        [33]])


In [82]:
### CHAPTER 1 - MODEL FROM SCRATCH

##SIMPLE LINEAL REGRESION ---> y = XW + b

# X = input data
# W = weight ----> knob
# b = bias   ----> knob
# y(y-hat) = our model´s prediction (our guess)

# W and b are the the "tools" or "knobs" our model can turn.
# Our goal is to find the perfect values fot them to  prediction y-hat as close as the real y as possible

# 5 STEP LOOP

In [102]:
## STEP 1 Create Data

#Our batch of data will have 10 data points
N = 10
#Each data point has 1 input feature and 1 output value
D_in = 1
D_out = 1

#Create our input data X
X = torch.randn(N, D_in)

#Create our true target labels y by using the "true" W and b
#The "true" W is 2.0, the "true" b is 1.0
true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1

#The model will never see the **true_W OR true_b**, its job is discover them just by looking at X AND y_true

print(y_true)

tensor([[-0.3629],
        [-1.9155],
        [ 2.3310],
        [ 1.9331],
        [ 0.4892],
        [ 2.6634],
        [ 0.6792],
        [ 1.0100],
        [ 1.6099],
        [ 2.0187]])


In [92]:
# MODEL´S BRAIN

# Initialize our parameters with random values.
# Shapes must be correct for matrix multiplication!

W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Initial Weight W:\n {W}")
print(f"Initial bias b:\n {b}")


Initial Weight W:
 tensor([[0.2085]], requires_grad=True)
Initial bias b:
 tensor([1.3656], requires_grad=True)


In [111]:
## IMPLEMNTATION FROM MATH TO CODE ##

# The math
# y = XW + b

# The code
# y_hat = X @ W + b

# Define model´s logic
def model(datos_entrada):
    return datos_entrada @ W + b


In [117]:
#Forward pass through our model
y_hat = model(X)

print(f"Prediction y_hat (first 3 rows):\n {y_hat[:3]}\n")
print(f"True Labels y_true( first 3 rows):\n {y_true[:3]}")

Prediction y_hat (first 3 rows):
 tensor([[1.2270],
        [1.0406],
        [1.5055]], grad_fn=<SliceBackward0>)

True Labels y_true( first 3 rows):
 tensor([[-0.3629],
        [-1.9155],
        [ 2.3310]])


In [119]:
## STEP 2 Quantify the error

# Mean Squared Error (MSE)
# loss = ((y_hat - y_true)**2).mean()

# Mean Squared Error (MSE)

# $$L = \frac{1}{N} \sum_{i=1}^{N} (\hat{y}_i - y_i)^2$$

#   1. Difference: Subtract the real value from the prediction: (y_hat - y)
#   2. Square: Square the result to make it positive: (y_hat - y)^2
#   3. Average: Calculate the mean of all squared differences: .mean()

#   Remember the "true" W is 2.0, the "true" b is 1.0


# Lets calculate the loss
error = y_hat - y_true
squared_error = error ** 2
loss = squared_error.mean()

print(f"Loss (Our single scorecard number): {loss}")

Loss (Our single scorecard number): 1.5042517185211182


In [120]:
# Compute grradients
loss.backward()

#The gradients are now stored in the .grad attribute
print(f"Gradient for W (aL/aW):\n {W.grad}\n")
print(f"Gradient for b (aL/ab):\n {b.grad}\n")

Gradient for W aL/aW):
 tensor([[-4.7565]])

Gradient for b aL/ab):
 tensor([1.9081])





$$\theta_{t+1} = \theta_t - \eta \cdot \nabla_\theta L$$

* **$\theta$ (theta):** Represents all our parameters. In our case, these are the "knobs" **W** and **b**.
* **$\eta$ (eta):** This is the **learning rate**. It is a small number (e.g., 0.01) that controls our step size.
* **$\nabla_\theta L$:** This is the gradient of the loss. We just calculated this using `.backward()`, and it is stored in `W.grad` and `b.grad`.

In [ ]:
# Updating the weights (W)
# W_new = W_old - learning_rate * W.grad

# Updating the bias (b)
# b_new = b_old - learning_rate * b.grad

In [121]:
# Hyperparameters
learning_rate, epochs = 0.01, 100

# Re-initialize parameters
W, b = torch.randn(1, 1, requires_grad=True), torch.randn(1, requires_grad=True)

# Training Loop
for epoch in range(epochs):
    # Forward pass and loss
    y_hat = X @ W + b
    loss = torch.mean((y_hat - y_true)**2)

    # Backward pass
    loss.backward()

    # Update parameters
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad

    # Zero gradients
    W.grad.zero_()
    b.grad.zero_()

    # ... (dentro del bucle/loop)
    if epoch % 10 == 0:
        print(f"Epoch {epoch:02d}: Loss={loss.item():.4f}, W={W.item():.3f}, b={b.item():.3f}")

print(f"\nFinal Parameters: W={W.item():.3f}, b={b.item():.3f}")
print(f"True Parameters:  W=2.000, b=1.000")

Epoch 00: Loss=5.3756, W=0.060, b=-0.839
Epoch 10: Loss=3.8811, W=0.221, b=-0.494
Epoch 20: Loss=2.8358, W=0.369, b=-0.212
Epoch 30: Loss=2.0983, W=0.505, b=0.019
Epoch 40: Loss=1.5727, W=0.630, b=0.208
Epoch 50: Loss=1.1941, W=0.744, b=0.362
Epoch 60: Loss=0.9182, W=0.848, b=0.489
Epoch 70: Loss=0.7147, W=0.944, b=0.592
Epoch 80: Loss=0.5626, W=1.032, b=0.677
Epoch 90: Loss=0.4476, W=1.112, b=0.746

Final Parameters: W=1.178, b=0.798
True Parameters:  W=2.000, b=1.000
